language: generic
os:
- linux
- osx
env:
  matrix:
  - CONDA_ENV=3.7
  - CONDA_ENV=3.6
sudo: false
jobs:
  include:
  - stage: lint
    os: linux
    script:
    - make lint
  - stage: docs
    os: linux
    install:
    - conda env create --file docs/source/environment.yml
    - conda activate landlag_rest_docs
    script:
    - sphinx-apidoc --force -o docs landlab_rest *tests
    - make -C docs clean html
  - stage: deploy
    if: tag =~ v.*$
    script: skip
    os: linux
    deploy:
      on:
        all_branches: true
      provider: pypi
      user: mcflugen
      password:
        secure: d0lVWG54WokY88HQJRll0hshZ9apboEHdrjjs9mZKbCu6qVADp4r6xkboUuS9W4nSAVDfKZ4Q7cPdkplfGunjuhPq4McztF7jWqc1zPwVvKfJiHhGK90vqwUJwLC/zyPn2QR3HYCTmainZeGGMcsGNh5IvO5CcZg9IGR3M/EsPm6WTTu+/e1JG6fixO+cUmYsQbQ/Z2/+NSHUiFkiT8oAlLJZqZDHvvURU4jQCBeISnqRzOqR76Sy00W1gniUYXeyr8DUAZy+SHPgxIQ8tUAkB/Qg6mwNVQ2P+VEkm1feuTNUbrUYyi34XZhcjvP6AQfU1sKIsdMQvCtBTfSO1ALNy+5izKUhi1egmoarqcV/HkMho/okSWDDCkrTiYMb1904rYaTH/x6ixcefFT4X1GBLthsF+ZRBvzCQSKxKPWt/Sqn8P9CyAOIVDSJIut/nII/LfkC50fKdIz4DMIb9vtGgyknHlRxj1a2pmAwTlBF7OXV/BKaEafxapaUmAnj/V+OdFsiHn9iA4xLaQ/YgYWjI6fveiWMD+Pl7KPUDt5eK7WtiI1bfsuyuKMlyTwyunkfqJ5Y24R6DTKBksYqNpuYmzAewHTbNcJkesN/ZPvDp1zSgmYQr/IlObTvxt57ebunxn+1rByN/gO48QeUMOr9LWPSaYdHcjQSN5ZHBMKpqI=
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n test_env python=$CONDA_ENV
- source activate test_env
install:
- pip install . -r requirements.txt
script:
- pytest --cov=landlab_rest --cov-report=xml:$(pwd)/coverage.xml -vvv
after_success: coveralls
